--- 

clone: 

  depth: 1

kind: pipeline

name: FiqriPipeline

steps: 

  - 

    commands: 

      - "curl https://raw.githubusercontent.com/Rombuilding-X00TD/kernel_build_script-droneci/main/droneci-release-X00T.sh | bash"

    environment: 

      TELEGRAM_TOKEN: 

        from_secret: BOT_API_KEY

    image: fadlyas/kernel_dockerfile:latest

    name: compile

    trigger: 

      branch: 

        - main
